### ISSUE TITLE
unable to deploy 

### ISSUE THREAD

**Issue by seshasaisrivatsav** [chenkie/angular-cli-heroku#3]
`https://thawing-woodland-25116.herokuapp.com/ | https://git.heroku.com/thawing-woodland-25116.git
seshas-MacBook-Pro:angular-cli-heroku sesha$ git add .
seshas-MacBook-Pro:angular-cli-heroku sesha$ git commit -m "asda"
[master 423c8da] asda
 Committer: sesha sai srivatsav kuchibhotla <sesha@seshas-MacBook-Pro.local>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 7022 insertions(+)
 create mode 100644 package-lock.json
seshas-MacBook-Pro:angular-cli-heroku sesha$ git push heroku master
Counting objects: 107, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (57/57), done.
Writing objects: 100% (107/107), 88.44 KiB | 0 bytes/s, done.
Total 107 (delta 45), reused 103 (delta 44)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote: 
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote: 
remote: -----> Installing binaries
remote:        engines.node (package.json):  6.9.2
remote:        engines.npm (package.json):   3.10.9
remote:        
remote:        Downloading and installing node 6.9.2...
remote:        npm 3.10.9 already installed with node
remote: 
remote: -----> Restoring cache
remote:        Skipping cache restore (new-signature)
remote: 
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:        
remote:        > execSync@1.0.2 install /tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/execSync
remote:        > node install.js
remote:        
remote:        [execsync v1.0.2] Attempting to compile native extensions.
remote:        [execSync v1.0.2]
remote:        Native code compile failed!!
remote:        
remote:        > node-zopfli@2.0.2 install /tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/node-zopfli
remote:        > node-pre-gyp install --fallback-to-build
remote:        
remote:        node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-
node-v48-linux-x64.tar.gz
remote:        node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@6.9.2 (node-v48 ABI) (f
alling back to source compile with node-gyp)
remote:        make: Entering directory '/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/node-zopfli/build'
remote:        CXX(target) Release/obj.target/zopfli/src/zopfli-binding.o
remote:        CXX(target) Release/obj.target/zopfli/src/png/zopflipng.o
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/blocksplitter.o
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/cache.o
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/deflate.o
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/gzip_container.o
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/hash.o
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/katajainen.o
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/lz77.o
remote:        In file included from ../zopfli/src/zopfli/lz77.c:21:0:
remote:        ../zopfli/src/zopfli/symbols.h:38:12: warning: ‘ZopfliGetDistExtraBits’ defined but not used [-Wunuse
d-function]
remote:        static int ZopfliGetDistExtraBits(int dist) {
remote:        ^
remote:        ../zopfli/src/zopfli/symbols.h:61:12: warning: ‘ZopfliGetDistExtraBitsValue’ defined but not used [-W
unused-function]
remote:        static int ZopfliGetDistExtraBitsValue(int dist) {
remote:        ^
remote:        ../zopfli/src/zopfli/symbols.h:138:12: warning: ‘ZopfliGetLengthExtraBits’ defined but not used [-Wun
used-function]
remote:        static int ZopfliGetLengthExtraBits(int l) {
remote:        ^
remote:        ../zopfli/src/zopfli/symbols.h:161:12: warning: ‘ZopfliGetLengthExtraBitsValue’ defined but not used 
[-Wunused-function]
remote:        static int ZopfliGetLengthExtraBitsValue(int l) {
remote:        ^
remote:        ../zopfli/src/zopfli/symbols.h:222:12: warning: ‘ZopfliGetLengthSymbolExtraBits’ defined but not used
 [-Wunused-function]
remote:        static int ZopfliGetLengthSymbolExtraBits(int s) {
remote:        ^
remote:        ../zopfli/src/zopfli/symbols.h:231:12: warning: ‘ZopfliGetDistSymbolExtraBits’ defined but not used [
-Wunused-function]
remote:        static int ZopfliGetDistSymbolExtraBits(int s) {
remote:        ^
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/squeeze.o
remote:        In file included from ../zopfli/src/zopfli/squeeze.c:28:0:
remote:        ../zopfli/src/zopfli/symbols.h:61:12: warning: ‘ZopfliGetDistExtraBitsValue’ defined but not used [-W
unused-function]
remote:        static int ZopfliGetDistExtraBitsValue(int dist) {
remote:        ^
remote:        ../zopfli/src/zopfli/symbols.h:161:12: warning: ‘ZopfliGetLengthExtraBitsValue’ defined but not used 
[-Wunused-function]
remote:        static int ZopfliGetLengthExtraBitsValue(int l) {
remote:        ^
remote:        ../zopfli/src/zopfli/symbols.h:222:12: warning: ‘ZopfliGetLengthSymbolExtraBits’ defined but not used
 [-Wunused-function]
remote:        static int ZopfliGetLengthSymbolExtraBits(int s) {
remote:        ^
remote:        ../zopfli/src/zopfli/symbols.h:231:12: warning: ‘ZopfliGetDistSymbolExtraBits’ defined but not used [
-Wunused-function]
remote:        static int ZopfliGetDistSymbolExtraBits(int s) {
remote:        ^
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/tree.o
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/util.o
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/zlib_container.o
remote:        CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/zopfli_lib.o
remote:        CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/zopflipng_lib.o
remote:        CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/lodepng/lodepng.o
remote:        CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/lodepng/lodepng_util.o
remote:        SOLINK_MODULE(target) Release/obj.target/zopfli.node
remote:        COPY Release/zopfli.node
remote:        COPY /tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/node-zopfli/lib/binding/node-v48-linux-
x64/zopfli.node
remote:        TOUCH Release/obj.target/action_after_build.stamp
remote:        make: Leaving directory '/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/node-zopfli/build'
remote:        
remote:        > node-sass@3.13.1 install /tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/node-sass
remote:        > node scripts/install.js
remote:        
remote:        Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-48_bind
ing.node
remote:        Download complete
remote:        Binary saved to /tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/node-sass/vendor/linux-x64-4
8/binding.node
remote:        Caching binary to /app/.npm/node-sass/3.13.1/linux-x64-48_binding.node
remote:        
remote:        > node-sass@3.13.1 postinstall /tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/node-sass
remote:        > node scripts/build.js
remote:        
remote:        Binary found at /tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/node-sass/vendor/linux-x64-4
8/binding.node
remote:        Testing binary
remote:        Binary is fine
remote:        
remote:        > angular-heroku@0.0.0 postinstall /tmp/build_ed485db58a8ad825d72fdc47dce27d29
remote:        > ng build --aot -prod
remote:        
remote:        Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "undefined".
remote:        Error: Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "undefined".
remote:        at Object.<anonymous> (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/@ngtools/webpack/src/
index.js:27:11)
remote:        at Module._compile (module.js:570:32)
remote:        at Object.Module._extensions..js (module.js:579:10)
remote:        at Module.load (module.js:487:32)
remote:        at tryModuleLoad (module.js:446:12)
remote:        at Function.Module._load (module.js:438:3)
remote:        at Module.require (module.js:497:17)
remote:        at require (internal/module.js:20:19)
remote:        at Object.<anonymous> (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/angular-cli/models/we
bpack-build-typescript.js:3:17)
remote:        at Module._compile (module.js:570:32)
remote:        at Object.Module._extensions..js (module.js:579:10)
remote:        at Module.load (module.js:487:32)
remote:        at tryModuleLoad (module.js:446:12)
remote:        at Function.Module._load (module.js:438:3)
remote:        at Module.require (module.js:497:17)
remote:        at require (internal/module.js:20:19)
remote:        at Object.<anonymous> (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/angular-cli/models/we
bpack-config.js:2:34)
remote:        at Module._compile (module.js:570:32)
remote:        at Object.Module._extensions..js (module.js:579:10)
remote:        at Module.load (module.js:487:32)
remote:        at tryModuleLoad (module.js:446:12)
remote:        at Function.Module._load (module.js:438:3)
remote:        at Module.require (module.js:497:17)
remote:        at require (internal/module.js:20:19)
remote:        at Object.<anonymous> (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/angular-cli/tasks/bui
ld-webpack.js:6:24)
remote:        at Module._compile (module.js:570:32)
remote:        at Object.Module._extensions..js (module.js:579:10)
remote:        at Module.load (module.js:487:32)
remote:        at tryModuleLoad (module.js:446:12)
remote:        at Function.Module._load (module.js:438:3)
remote:        at Module.require (module.js:497:17)
remote:        at require (internal/module.js:20:19)
remote:        at Object.<anonymous> (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/angular-cli/commands/
build.js:3:23)
remote:        at Module._compile (module.js:570:32)
remote:        at Object.Module._extensions..js (module.js:579:10)
remote:        at Module.load (module.js:487:32)
remote:        at tryModuleLoad (module.js:446:12)
remote:        at Function.Module._load (module.js:438:3)
remote:        at Module.require (module.js:497:17)
remote:        at require (internal/module.js:20:19)
remote:        at Class.includedCommands (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/angular-cli/addon
/index.js:21:16)
remote:        at /tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/angular-cli/angular-cli/lib/models/projec
t.js:392:61
remote:        at Array.forEach (native)
remote:        at Project.addonCommands (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/angular-cli/angula
r-cli/lib/models/project.js:391:15)
remote:        at Project.eachAddonCommand (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/angular-cli/ang
ular-cli/lib/models/project.js:426:30)
remote:        at module.exports (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/angular-cli/angular-cli/l
ib/cli/lookup-command.js:33:13)
remote:        at CLI.<anonymous> (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/angular-cli/angular-cli/
lib/cli/cli.js:34:26)
remote:        at tryCatch (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/rsvp/dist/rsvp.js:525:12)
remote:        at invokeCallback (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/rsvp/dist/rsvp.js:538:13)
remote:        at publish (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/rsvp/dist/rsvp.js:508:7)
remote:        at flush (/tmp/build_ed485db58a8ad825d72fdc47dce27d29/node_modules/rsvp/dist/rsvp.js:2400:5)
remote:        at _combinedTickCallback (internal/process/next_tick.js:67:7)
remote:        at process._tickCallback (internal/process/next_tick.js:98:9)
remote:        
remote:        npm ERR! Linux 3.13.0-123-generic
remote:        npm ERR! argv "/tmp/build_ed485db58a8ad825d72fdc47dce27d29/.heroku/node/bin/node" "/tmp/build_ed485db
58a8ad825d72fdc47dce27d29/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_ed485db58a8ad82
5d72fdc47dce27d29/.npmrc"
remote:        npm ERR! node v6.9.2
remote:        npm ERR! npm  v3.10.9
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! angular-heroku@0.0.0 postinstall: `ng build --aot -prod`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the angular-heroku@0.0.0 postinstall script 'ng build --aot -prod'.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the angular-heroku package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     ng build --aot -prod
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs angular-heroku
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!     npm owner ls angular-heroku
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_ed485db58a8ad825d72fdc47dce27d29/npm-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to thawing-woodland-25116.
remote: 
To https://git.heroku.com/thawing-woodland-25116.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/thawing-woodland-25116.git'
seshas-MacBook-Pro:angular-cli-heroku sesha$ heroku logs
2017-07-17T20:32:48.478828+00:00 app[api]: Release v1 created by user seshasaisrivatsav@gmail.com
2017-07-17T20:32:48.478828+00:00 app[api]: Initial release by user seshasaisrivatsav@gmail.com
2017-07-17T20:32:48.590360+00:00 app[api]: Enable Logplex by user seshasaisrivatsav@gmail.com
`

**Comment by chenkie** [comment]
I just updated the repo to use the latest version of Angular. Can you try it again and see if it works now?

**Comment by LayCraft** [comment]
I have been trying to fix a similar error. I am submitting a pull request for what fixed it for me.
